service:
    attribution:
        text: "©Omniscale 2010 (http://omniscale.de) – Map data: CC-BY-SA OpenStreetMap and Contributors"
    md:
        title: MapProxy WMS Proxy
        abstract: This is the fantastic MapProxy.
        online_resource: http://mapproxy.org/
        contact:
            person: Your Name Here
            position: Technical Director
            organization: 
            address: Fakestreet 123
            city: Somewhere
            postcode: 12345
            country: Germany
            phone: +49(0)000-000000-0
            fax: +49(0)000-000000-0
            email: info@omniscale.de
        access_constraints:
            This service is intended for private and evaluation use only.
            The data is licensed as Creative Commons Attribution-Share Alike 2.0
            (http://creativecommons.org/licenses/by-sa/2.0/)
        fees: 'None'

layers:
    # ###########################################
    # # server with two data sources
    # # configured for use in regular WMS clients
    # ###########################################
    # merged:
    #     md:
    #         title: Merged server
    #     param:
    #       # cache tiles in format:
    #       # format: image/png
    #       
    #       # cache projected and geographical SRS
    #       srs: ['EPSG:4326', 'EPSG:900913']
    #       
    #       # store another level between each regular level
    #       res: 'sqrt2'
    #       
    #       # request all data in this format:
    #       request_format: image/tiff
    #       
    #       # use a tile size of:
    #       tile_size: [512, 512]
    #       
    #     sources:
    #     - type: cache_wms
    #       req:
    #         url: http://server1/mapserver/service?
    #         layers: base
    #     - type: cache_wms
    #       req:
    #         url: http://server2/mapserver/service?
    #         layers: roads

    # # #########################
    # # # Layer from TMS Source
    # # #########################
    # osm:
    #     md:
    #         title: osm.omniscale.net - Open Street Map
    #    attribution:
    #        # text for this layer
    #        text: ""
    #        # if inverse: use white on black attribution. for aerial images
    #        # inverse: False
    #     watermark:
    #         # add the following text on each tile
    #         text: Omniscale
    #     sources:
    #     - type: cache_tms
    #       # is the tile coordinate origin (0, 0) in the lower left corner? otherwise top left.
    #       ll_origin: True
    #       url: http://osm.omniscale.net/proxy/tms/osm_EPSG900913

    # ###########################################
    # # overlay layer
    # ###########################################
    # roads:
    #     md:
    #         title: transparent overlay
    #     param:
    #       srs: 'EPSG:900913'
    #     sources:
    #     - type: cache_wms
    #       req:
    #         url: http://server/mapserver/service?
    #         layers: roads
    #         transparent: 'true'
    
    # #########################
    # # Layer from TMS Source
    # #########################
    osm:
        md:
            title: Omniscale OSM WMS - osm.omniscale.net
        param:
            # cache tiles in format:
            # format: image/png
            
            # cache projected and geographical SRS
            srs: ['EPSG:4326', 'EPSG:900913']
            
            # store another level between each regular level
            res: 'sqrt2'
            
            # request all data in this format:
            # request_format: image/png
            
            # use a tile size of:
            tile_size: [512, 512]
        sources:
        - type: cache_wms
          req:
            url: http://osm.omniscale.net/proxy/service?
            layers: osm
            # styles:
            # transparent: False
